// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8Cf8UCo-CcXcEhDtjxEIwiBhjI8bx5E',
    appId: '1:487442618923:web:5a4541ee0781d90274286e',
    messagingSenderId: '487442618923',
    projectId: 'controle-gestao-ea7ad',
    authDomain: 'controle-gestao-ea7ad.firebaseapp.com',
    storageBucket: 'controle-gestao-ea7ad.firebasestorage.app',
    measurementId: 'G-NBJSLN5471',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbE8kReDTTZyEpjSlj3VFmRUhLQumiNc',
    appId: '1:487442618923:android:76daa2e2a5b3c51574286e',
    messagingSenderId: '487442618923',
    projectId: 'controle-gestao-ea7ad',
    storageBucket: 'controle-gestao-ea7ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRhOjsmGtB0PHwA7qJVrj5I4kp7H5tZk',
    appId: '1:487442618923:ios:44a7e99d3438d16d74286e',
    messagingSenderId: '487442618923',
    projectId: 'controle-gestao-ea7ad',
    storageBucket: 'controle-gestao-ea7ad.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
